### ISSUE TITLE
Links inside BXslider are not working in Firefox 59+!

### ISSUE THREAD

**Issue by timomayer** [virtualidentityag/bx-slider-4-4.2.x#3]

**Comment by timomayer** [comment]
https://www.mozilla.org/en-US/firefox/59.0/releasenotes/ 

vielleicht
"Added support for W3C specs for pointer events and improved platform integration with added device support for mouse, pen, and touch screen pointer Input"

**Comment by jhadenfeldt** [comment]
Same issue as described in https://github.com/stevenwanderski/bxslider-4/issues/1188#issuecomment-373488113. The proposed solution works for now, does seem like a quickfix though. 
I will investigate more tomorrow.
